version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(ci)"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "nix"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 2 * * *"
      timezone: "America/Chicago"
    commit-message:
      prefix: "build(flake.lock)"
