keys:
  - &jaden E305DD83FAD97046634575BF66E3C3D45EA5C756
  - &users
    - &jaden_user age1hsfn62lep9qlxpa22u0shunsg3ymf3kq7gym0ujv43fndcpne4uslxx2t4
  - &hosts:
    - &asrock age1j73l6s7lhv646p752yftfz568e9yedjndfu45fmr7su04cwx74gsm0u4zd
    - &thinkpadx1 age1xvh0vt6fev9syrvglf3hr2hppl4gzr3mrdu5dde0474pndvmwd9s7uamqc
    - &dokja age19pguxlu4ga2nfvrga8jhz0p0qr632knut9w6qg8dh50uwe4d7qpqjdmrdx
creation_rules:
  - path_regex: ^secrets/hosts/dokja.yml$
    key_groups:
      - pgp:
          - *jaden
        age:
          - *dokja
