keys:
  - &jaden E305DD83FAD97046634575BF66E3C3D45EA5C756
  - &users
    - &jaden_user age1hsfn62lep9qlxpa22u0shunsg3ymf3kq7gym0ujv43fndcpne4uslxx2t4
  - &hosts:
    - &asrock age1j73l6s7lhv646p752yftfz568e9yedjndfu45fmr7su04cwx74gsm0u4zd
    - &thinkpadx1 age1xvh0vt6fev9syrvglf3hr2hppl4gzr3mrdu5dde0474pndvmwd9s7uamqc
    - &dokja age19pguxlu4ga2nfvrga8jhz0p0qr632knut9w6qg8dh50uwe4d7qpqjdmrdx
    - &teemo age1jztn2kejg09xsrxzf6nxm26wgpylxgq5wqjrnd5putgjd9w2yfps0wtjdm
    - &aesop age182yphg6rgfaqpnu6ldmq2e0fpgllj2dgg8qtjkkc6p54wrqdfgrs70r2zd
creation_rules:
  - path_regex: ^secrets/hosts/aesop.yml$
    key_groups:
      - pgp:
          - *jaden
        age:
          - *aesop
  - path_regex: ^secrets/hosts/dokja.yml$
    key_groups:
      - pgp:
          - *jaden
        age:
          - *dokja
  - path_regex: ^secrets/hosts/teemo.yml$
    key_groups:
      - pgp:
          - *jaden
        age:
          - *teemo
  - path_regex: ^hosts/teemo/actual.key$
    key_groups:
      - pgp:
          - *jaden
        age:
          - *teemo
  - path_regex: ^secrets/hosts/aesop-dokja.yml$
    key_groups:
      - pgp:
          - *jaden
        age:
          - *aesop
          - *dokja
  - path_regex: ^secrets/hosts/dokja-teemo.yml$
    key_groups:
      - pgp:
          - *jaden
        age:
          - *dokja
          - *teemo
